{{ if not .Values.ingress.enabled }}
{{- return -}}
{{- end }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "fullName" . }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "fullName" . }}
            port:
              number: 8080
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ include "fullName" . }}-cert
