apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullName" . }}
spec:
  type: ClusterIP
  selector:
    {{- include "selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
