providers:  # @schema additionalProperties: false
  kubernetesGateway:
    # -- Enable Traefik Gateway provider for Gateway API
    enabled: true

gateway:
  enabled: true
  listeners:
    websecure:
      # -- Port is the network port. Multiple listeners may use the same port, subject to the Listener compatibility rules.
      # The port must match a port declared in ports section.
      port: 8443
      # -- Optional hostname. See [Hostname](https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io/v1.Hostname)
      # hostname:
      # Specify expected protocol on this listener See [ProtocolType](https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io/v1.ProtocolType)
      protocol: HTTPS
      # -- Add certificates for TLS or HTTPS protocols. See [GatewayTLSConfig](https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io%2fv1.GatewayTLSConfig)
      certificateRefs:
        - name: traefik-gw-cert # This must match the secretName from your Certificate
          kind: Secret
          group: "" # The group for Secret resources is empty
          namespace: traefik # The namespace where the secret is located

ingressRoute:
  dashboard:
    # -- Create an IngressRoute for the dashboard
    enabled: true

ports:
  websecure:
    ## -- Enable this entrypoint as a default entrypoint. When a service doesn't explicitly set an entrypoint it will only use this entrypoint.
    asDefault: true
